name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "2.15.0"
description = "A hardcore quest-based Minecraft 1.7.10 modpack centered on Nuclear Tech Mod."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e8e2dc66d10ec13fd12958afb368c89de70d35af36eebef3ef86e2fc8576b66"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
