name = "Nuclear Tech: New Horizons"
author = "Bufka2011"
version = "2.15.0"
description = "A big progressive questing modpack for Minecraft 1.7.10 balanced around the NTM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8209b364b7bba7c1a1533b81dc5a3e4649467f83efed02f1de7697a8870e1d5"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
